server:
  port: 10088

spring:
  application:
    name: rabbitMq
  datasource:
    url: jdbc:mysql://192.168.110.173:3306/leyou
    username: root
    password: Ge_shangkun1
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 192.168.110.173

  rabbitmq:
    host: 192.168.110.173
    username: leyou
    password: leyou
    virtual-host: /leyou
    listener:
      simple:
        retry:
          enabled: true #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          max-attempts: 5 #最大重试次数
          initial-interval: 5000 #重试间隔时间（单位毫秒）
          max-interval: 1200000 #重试最大时间间隔（单位毫秒）
          multiplier: 5 #应用于前一重试间隔的乘法器。
