server:
  port: 10086
spring:
  datasource:
    url: jdbc:mysql://192.168.0.112:3306/db_flash_correct?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: Ge_shangkun1

mybatis:
  type-aliases-package: com.gsk.com.gsk.mybatis.com.gsk.pojo.pojo
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true

